theme: jekyll-theme-minimal
plugins:
  - jemoji
markdown: kramdown


logo: images/logo_page.jpg
title: "Decoding NER Biases"
description: "This project tries to explore potential biases in NER algorithms."