theme: jekyll-theme-minimal
plugins:
  - jemoji
markdown: kramdown

title: [Deconding_NER_Biases]
description: [This project tries to explore potential biases in NER algorithms.
It was made during a Sciences Po course called '*Decoding Biases in AI*'.
**Group Members:**
> Eleonora BONEL, Ryan HACHEM, Adrien HANS, Sara KEMPPAINEN, Pablo PIGUET]