theme: jekyll-theme-minimal
plugins:
  - jemoji
markdown: kramdown


logo: images/log_page.jpeg
title: "Decoding NER Biases"
description: "This project tries to explore potential biases in NER algorithms."